# Hugo configuration

title: NJU Astrometry Group
baseURL: 'https://njuastrometry.github.io/'

# Languages

defaultContentLanguage: en
defaultContentLanguageInSubdir: true
hasCJKLanguage: true
removePathAccents: true

# General settings

enableGitInfo: false
summaryLength: 30

pagination:
  pagerSize: 10

enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: '<sup>^</sup>'

ignoreFiles:
  - '\.ipynb$'
  - '(^|/)\.ipynb_checkpoints(/|$)'
  - '\.Rmd$'
  - '\.Rmarkdown$'
  - '(^|/)_cache(/|$)'

# URL structure and redirects

permalinks:
  authors: '/author/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'

disableAliases: false

# Output formats

outputs:
  home: [HTML, RSS, JSON, WebAppManifest]
  section: [HTML, RSS]

# Image processing

imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart

timeout: '600s'

# Taxonomies

taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors

# Inherit theme configuration

markup:
  _merge: deep

security:
  _merge: deep

sitemap:
  _merge: deep

# Related content

related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70