# Languages

en:
  languageCode: en-us
  languageName: English
  contentDir: content/en

zh:
  languageCode: zh-Hans
  languageName: 中文
  contentDir: content/zh
  title: 南大天体测量课题组
  params:
    description: 南京大学天文参考系与高精度天体测量课题组网站。
