# Languages
# Content translations use filename suffixes:
# index.md / index.zh.md

en:
  languageCode: en-US
  languageName: English
  title: NJU Astrometry Group
  weight: 1

zh:
  languageCode: zh-Hans
  languageName: 中文
  title: 南大天体测量课题组
  weight: 2