main:
  - name: About
    url: tour
    weight: 10
  - name: News
    url: post
    weight: 20
  - name: People
    url: people
    weight: 30
  - name: Events
    url: event
    weight: 40
  - name: Projects
    url: project
    weight: 50
  - name: Publications
    url: publication
    weight: 60
  - name: Contact
    url: contact
    weight: 70
