main:
  - name: 简介
    url: tour
    weight: 10
  - name: 最新动态
    url: post
    weight: 20
  - name: 课题组成员
    url: people
    weight: 30
  - name: 新闻
    url: event
    weight: 40
  - name: 科研项目
    url: project
    weight: 50
  - name: 研究成果
    url: publication
    weight: 60
  - name: 联系我们
    url: contact
    weight: 70
