main:
  - name: Home
    url: /
    weight: 10

  - name: Projects
    url: project
    weight: 15

  - name: Posts
    url: post
    weight: 20

  - name: People
    url: people
    weight: 30

  - name: Events
    url: event
    weight: 40

  - name: Publications
    url: publication
    weight: 50

  - name: Contact
    url: contact
    weight: 60

  # Optional:
  # - name: Data & Tools
  #   url: resources
  #   weight: 28
