name        = "NJU Astrometry Group"
description = "Website for the Astronomical Reference System & High-Precision Astrometry Group at Nanjing University—news, publications, people, and resources."
homepage    = "https://njuastrometry.github.io/"
demosite    = "https://njuastrometry.github.io/"

# Keep the correct license for the starter you built on (Wowchemy is MIT).
license     = "MIT"
licenselink = "https://github.com/wowchemy/starter-hugo-research-group/blob/main/LICENSE.md"

# Keep this list tight—only what you ship (improves theme discovery and clarity).
tags = [
  "research",
  "publications",
  "people",
  "news",
  "events",
  "search",
  "multilingual",
  "math",
  "darkmode"
]

features = [
  "seo",
  "opengraph",
  "research publication system",
  "widgets",
  "search",
  "gallery",
  "slides"
]

# Guard against building with too-old Hugo versions.
min_version = "0.135.0"

[author]
  name     = "Niu Liu"
  homepage = "https://njuastrometry.github.io/en/"

# Acknowledge upstream template provenance.
[original]
  name     = "Wowchemy (Research Group Starter)"
  homepage = "https://wowchemy.com/"
  repo     = "https://github.com/wowchemy/starter-hugo-research-group"
