# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

en:
  languageCode: en-us
  languageName: English
  contentDir: content/en
  weight: 1
  params:
    # Optional per-language overrides:
    # description: "Astrometry & reference frames (Gaia/VLBI) research group."

zh:
  languageCode: zh-Hans
  languageName: 中文
  contentDir: content/zh
  weight: 2
  title: 南大天体测量课题组
  params:
    description: "南京大学天文参考系与高精度天体测量课题组"

