main:
  - name: 主页
    url: /
    weight: 10

  - name: 科研项目
    url: project
    weight: 15

  - name: 最新动态
    url: post
    weight: 20

  - name: 课题组成员
    url: people
    weight: 30

  - name: 学术活动
    url: event
    weight: 40

  - name: 论文发表
    url: publication
    weight: 50

  - name: 联系我们
    url: contact
    weight: 60

  # 可选：
  # - name: 数据与工具
  #   url: resources
  #   weight: 28
