name: Import Publications From BibTeX

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: [ main ]
    paths:
      - 'data/publications.bib'   # <- put your .bib here (recommended by Hugo Blox)
  workflow_dispatch:

jobs:
  import:
    if: github.repository_owner != 'HugoBlox'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install CLI
        run: |
          echo "academic==0.10.0" > requirements.txt
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Convert BibTeX → Markdown
        # Only run if the .bib exists (handles deletes/renames gracefully)
        if: ${{ hashFiles('data/publications.bib') != '' }}
        run: |
          academic import data/publications.bib content/publication/ --compact

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'content: import publications from BibTeX'
          title: 'Import latest publications (BibTeX → Markdown)'
          body: |
            Import the latest publications from `data/publications.bib` to `content/publication/`.
            将最新的出版物从 `data/publications.bib` 导入到 `content/publication/`。
            Docs: https://docs.hugoblox.com/reference/content-types/
          base: main
          labels: automated-pr, content
          branch: hugoblox-import-publications
          delete-branch: true

      - name: PR info
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "PR #${{ steps.cpr.outputs.pull-request-number }}"
          echo "URL: ${{ steps.cpr.outputs.pull-request-url }}"
